# -*- coding: utf-8 -*-
"""Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTUs_JQvMgOqN8xw-puIpG21BfePENgD

# Deep Learning 基礎講座　最終課題: 脳波分類

## 概要
被験者が画像を見ているときの脳波から，その画像がどのカテゴリに属するかを分類するタスク．
- サンプル数: 訓練 118,800 サンプル，検証 59,400 サンプル，テスト 59,400 サンプル
- クラス数: 5
- 入力: 脳波データ（チャンネル数 x 系列長）
- 出力: 対応する画像のクラス
- 評価指標: Top-1 accuracy

### 元データセット ([Gifford2022 EEG dataset](https://osf.io/3jk45/)) との違い

- 本コンペでは難易度調整の目的で元データセットにいくつかの改変を加えています．

1. 訓練セットのみの使用
  - 元データセットでは訓練データに存在しなかったクラスの画像を見ているときの脳波においてテストが行われますが，これは難易度が非常に高くなります．
  - 本コンペでは元データセットの訓練セットを再分割し，訓練時に存在した画像に対応する別の脳波において検証・テストを行います．

2. クラス数の減少
  - 元データセット（の訓練セット）では16,540枚の画像に対し，1,654のクラスが存在します．
    - e.g. `aardvark`, `alligator`, `almond`, ...
  - 本コンペでは1,654のクラスを，`animal`, `food`, `clothing`, `tool`, `vehicle`の5つにまとめています．
    - e.g. `aardvark -> animal`, `alligator -> animal`, `almond -> food`, ...

### 考えられる工夫の例

- 音声モデルの導入
  - 脳波と同じ波である音声を扱うアーキテクチャを用いることが有効であると知られています．
  - 例）Conformer [[Gulati+ 2020](https://arxiv.org/abs/2005.08100)]
- 画像データを用いた事前学習
  - 本コンペのタスクは脳波のクラス分類ですが，配布してある画像データを脳波エンコーダの事前学習に用いることを許可します．
  - 例）CLIP [Radford+ 2021]
  - 画像を用いる場合は[こちら](https://osf.io/download/3v527/)からダウンロードしてください．
- 過学習を防ぐ正則化やドロップアウト

## 修了要件を満たす条件
- ベースラインモデルのbest test accuracyは38.8%となります．**これを超えた提出のみ，修了要件として認めます**．
- ベースラインから改善を加えることで，55%までは性能向上することを運営で確認しています．こちらを 1 つの指標として取り組んでみてください．

## 注意点
- 最終的な予測モデルは，**配布している訓練データを用いて学習**（ファインチューニング含む）したものとしてください．
- 学習を行わず，**事前学習済みモデルの知識のみを利用した推論は禁止**します．  
（例: ChatGPT 等の LLM に入力して推論を得るのみ）

### 事前学習モデルの利用
許可される事項
- **構成要素としての事前学習モデルの利用**: 自身で実装したアーキテクチャの一部（特徴抽出，埋め込みなど）として事前学習モデル（BERT，ViT など）を利用することは可能です．
- **ファインチューニング**: 上記の用途で利用している事前学習モデルのファインチューニングは可能です．

禁止される事項  
- **タスク解決用の事前学習モデルの利用**: transformers などで提供されている，対象タスクを直接解くための事前学習モデルでそのまま推論のみ，またはファインチューニングのみで利用することは禁止とします．
  - 禁止事項の例: VQA タスクを直接解くための事前学習モデルを VQA タスクで利用する．

## 1.準備
"""

# omnicampus 実行用
!pip install ipywidgets

# ライブラリのインポートとシード固定
import os, sys
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.utils as utils
import torch.nn.functional as F
from torch.utils.tensorboard import SummaryWriter
from einops.layers.torch import Rearrange
from einops import repeat
from glob import glob
from termcolor import cprint
from tqdm.notebook import tqdm
import math
os.environ["CUDA_LAUNCH_BLOCKING"] = "1"

SEED = 0
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# ドライブのマウント（Colabの場合）
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# ワーキングディレクトリを作成し移動．ノートブックを配置したディレクトリに適宜書き換え
WORK_DIR = "/content/drive/MyDrive/Colab Notebooks/最終課題"
os.makedirs(WORK_DIR, exist_ok=True)
# %cd {WORK_DIR}

"""## 2.データセット

ノートブックと同じディレクトリに`data/`が存在することを確認してください．
"""

class ThingsEEGDataset(torch.utils.data.Dataset):
    def __init__(self, split: str) -> None:
        super().__init__()

        assert split in ["train", "val", "test"], f"Invalid split: {split}"
        self.split = split
        self.num_classes = 5
        self.num_subjects = 10

        # データの読み込み
        self.X = np.load(f"data/{split}/eeg.npy")
        self.subject_idxs = np.load(f"data/{split}/subject_idxs.npy")

        # 正規化 (Z-score Normalization) ---
        # チャンネルごとに平均と標準偏差を計算してスケーリング
        # (サンプル数, チャンネル数, 系列長) のチャンネル軸(1)と系列軸(2)で計算
        mean = self.X.mean(axis=(0, 2), keepdims=True)
        std = self.X.std(axis=(0, 2), keepdims=True)
        self.X = (self.X - mean) / (std + 1e-6)

        self.X = torch.from_numpy(self.X).to(torch.float32)
        self.subject_idxs = torch.from_numpy(self.subject_idxs)

        if split in ["train", "val"]:
            self.y = np.load(f"data/{split}/labels.npy")
            self.y = torch.from_numpy(self.y)

        print(f"EEG: {self.X.shape}, labels: {self.y.shape if hasattr(self, 'y') else None}, subject indices: {self.subject_idxs.shape}")

    def __len__(self) -> int:
        return len(self.X)

    def __getitem__(self, i):
        x = self.X[i]

        # --- 改善ポイント2: データ拡張 (訓練時のみ) ---
        if self.split == "train":
            # 1. 微小なガウスノイズの付与 ( 頑健性の向上)
            if np.random.rand() < 0.5:
                noise = torch.randn_like(x) * 0.01
                x = x + noise

            # 2. ランダムな時間シフト (時系列データ特有の拡張)
            if np.random.rand() < 0.5:
                shift = np.random.randint(-10, 10)
                x = torch.roll(x, shifts=shift, dims=-1)
        if hasattr(self, "y"):
            return self.X[i], self.y[i], self.subject_idxs[i]
        else:
            return self.X[i], self.subject_idxs[i]

    @property
    def num_channels(self) -> int:
        return self.X.shape[1]

    @property
    def seq_len(self) -> int:
        return self.X.shape[2]

"""## 3.ベースラインモデル"""

#tranceformer用の位置エンコーディング
class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=500):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        # x shape: [Batch, Seq, Dim]
        x = x + self.pe[:, :x.size(1)]
        return x

class DeepEEGBlock(nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size=15, p_drop=0.3):
        super().__init__()
        # 時間方向の抽出
        self.conv_stem = nn.Sequential(
            nn.Conv1d(in_channels, out_channels, kernel_size=kernel_size, padding="same", bias=False),
            nn.BatchNorm1d(out_channels),
            nn.GELU(),
            nn.Dropout(p_drop)
        )
        # 残差接続用の調整
        self.shortcut = nn.Conv1d(in_channels, out_channels, kernel_size=1) if in_channels != out_channels else nn.Identity()

    def forward(self, x):
        return self.temporal(x) + self.shortcut(x)

class ImprovedEEGClassifier(nn.Module):
    def __init__(self, num_classes, num_channels, seq_len, hid_dim=128, nhead=8, num_layers=4):
        super().__init__()

        # 1. 空間フィルタリング (チャンネル間の情報を統合)
        #!D Convでチャンネル間の情報を統合しつつ次元を上げる
        self.conv_stem = nn.Sequential(
            nn.Conv1d(num_channels, hid_dim, kernel_size=15, padding=7, stride=1),
            nn.BatchNorm1d(hid_dim),
            nn.GELU(),
            nn.Dropout(0.2)
        )

# Transformer層 
        self.pos_encoder = PositionalEncoding(hid_dim, max_len=seq_len)

        encoder_layer = nn.TransformerEncoderLayer(
            d_model=hid_dim,
            nhead=nhead,
            dim_feedforward=hid_dim * 4,
            dropout=0.3,
            activation='gelu',
            batch_first=True
        )
        self.transformer = nn.TransformerEncoder(encoder_layer, num_layers=num_layers)

        # 分類ヘッド (MLP構成)
        self.head = nn.Sequential(
            nn.LayerNorm(hid_dim),
            nn.Linear(hid_dim, hid_dim // 2),
            nn.GELU(),
            nn.Dropout(0.5),
            nn.Linear(hid_dim // 2, num_classes)
        )

    def forward(self, x):
        # x: [Batch, Channels, Seq]
        x = self.conv_stem(x)

        # Transformer用に次元を入れ替え [Batch, Seq, Dim]
        x = x.permute(0, 2, 1)
        x = self.pos_encoder(x)

        # Transformerでの特徴抽出
        x = self.transformer(x) # [Batch, Seq, Dim]

        # 全時間軸の平均をとる (Global Average Pooling)
        x = x.mean(dim=1)

        return self.head(x)

"""## 4.訓練実行"""

# ハイパラ
lr = 0.0001
batch_size = 256
epochs = 50

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ------------------
#    Dataloader
# ------------------
train_set = ThingsEEGDataset("train") # ThingsMEGDataset("train")
train_loader = torch.utils.data.DataLoader(
    train_set, batch_size=batch_size, shuffle=True
)
val_set = ThingsEEGDataset("val") # ThingsMEGDataset("val")
val_loader = torch.utils.data.DataLoader(
    val_set, batch_size=batch_size, shuffle=False
)

# ------------------
#       Model
# ------------------
model = ImprovedEEGClassifier(
    num_classes=train_set.num_classes,
    num_channels=train_set.num_channels,
    seq_len=train_set.seq_len
).to(device)

def accuracy(y_pred, y):
    return (y_pred.argmax(dim=-1) == y).float().mean()



# ------------------
#     Optimizer
# ------------------
# OptimizerにWeight Decay(L2正則化)を追加して過学習を防ぐ
optimizer = torch.optim.AdamW(model.parameters(), lr=lr, weight_decay=0.05)

#学習率スケジューラー
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=100)

#損失関数
criterion = nn.CrossEntropyLoss()

# ------------------
#   Start training
# ------------------
# --- 事前準備 (訓練ループの外で定義) ---
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
max_val_acc = 0.0

# 1. 損失関数にラベルスムージングを適用 (過学習抑制)
criterion = nn.CrossEntropyLoss(label_smoothing=0.1)

# 2. スケジューラの定義 (学習率を徐々に下げる)
# optimizerは定義済みとします (AdamW などを推奨)
scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=epochs)

writer = SummaryWriter("tensorboard")

# --- Start Training ---
for epoch in range(epochs):
    print(f"Epoch {epoch+1}/{epochs}")
    train_loss, train_acc = [], []
    val_loss, val_acc = [], []

    # --- 訓練フェーズ ---
    model.train()
    for X, y, subject_idxs in tqdm(train_loader, desc="Train"):
        X, y = X.to(device), y.to(device)

        # 順伝播
        y_pred = model(X)
        loss = criterion(y_pred, y) # ラベルスムージング付き損失

        # 逆伝播
        optimizer.zero_grad()
        loss.backward()

        # 3. 勾配クリッピング (Transformerの学習を安定させる)
        utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

        optimizer.step()

        # 統計
        train_loss.append(loss.item())
        train_acc.append(accuracy(y_pred, y).item())

    # --- バリデーションフェーズ ---
    model.eval()
    with torch.no_grad():
        for X, y, subject_idxs in tqdm(val_loader, desc="Validation"):
            X, y = X.to(device), y.to(device)

            y_pred = model(X)

            v_loss = criterion(y_pred, y)
            val_loss.append(v_loss.item())
            val_acc.append(accuracy(y_pred, y).item())

    # --- 4. スケジューラの更新 (エポックごと) ---
    scheduler.step()
    current_lr = optimizer.param_groups[0]['lr']

    # 平均値の計算
    avg_train_loss = np.mean(train_loss)
    avg_train_acc = np.mean(train_acc)
    avg_val_loss = np.mean(val_loss)
    avg_val_acc = np.mean(val_acc)

    # ログ出力
    print(f"Epoch {epoch+1} | LR: {current_lr:.6f} | "
          f"Train Acc: {avg_train_acc:.3f} | Val Acc: {avg_val_acc:.3f}")

    # TensorBoardへの記録
    writer.add_scalar("Loss/train", avg_train_loss, epoch)
    writer.add_scalar("Accuracy/train", avg_train_acc, epoch)
    writer.add_scalar("Loss/val", avg_val_loss, epoch)
    writer.add_scalar("Accuracy/val", avg_val_acc, epoch)

    # --- 5. 最良モデルの保存ロジック ---
    # 直近のモデルを保存
    torch.save(model.state_dict(), "model_last.pt")

    # 最高精度を更新した場合のみ保存
    if avg_val_acc > max_val_acc:
        max_val_acc = avg_val_acc
        from termcolor import cprint # 警告回避のため
        cprint(f"★ New Best Accuracy: {max_val_acc:.4f}! Saving model_best.pt", "cyan")
        torch.save(model.state_dict(), "model_best.pt")

writer.close()

# Commented out IPython magic to ensure Python compatibility.
# %load_ext tensorboard
# %tensorboard --logdir tensorboard

"""## 5.評価"""

# ------------------
#    Dataloader
# ------------------
test_set = ThingsEEGDataset("test")
test_loader = torch.utils.data.DataLoader(
    test_set, batch_size=batch_size, shuffle=False
)

# ------------------
#       Model
# ------------------
model = ImprovedEEGClassifier(
    test_set.num_classes, test_set.seq_len, test_set.num_channels
).to(device)
model.load_state_dict(torch.load("model_best.pt", map_location="cuda"))

# ------------------
#  Start evaluation
# ------------------
preds = []
model.eval()
for X, subject_idxs in tqdm(test_loader, desc="Evaluation"):
    preds.append(model(X.to(device)).detach().cpu())

preds = torch.cat(preds, dim=0).numpy()
np.save("submission", preds)
print(f"Submission {preds.shape} saved.")

"""## 提出方法

以下の3点をzip化し，Omnicampusの「最終課題 (EEG)」から提出してください．

- `submission.npy`
- `model_last.pt`や`model_best.pt`など，テストに使用した重み（拡張子は`.pt`のみ）
- 本Colab Notebook
"""

from zipfile import ZipFile

model_path = "model_best.pt"
notebook_path = "DLBasics2025_competition_EEG_baseline.ipynb"

with ZipFile("submission.zip", "w") as zf:
    zf.write("submission.npy")
    zf.write(model_path)
    zf.write(notebook_path)

